### ISSUE TITLE
Who Are you?

### ISSUE THREAD

**Issue by Bashamega** [Rubiidev-18/rubiitubevercel#1]
Hello:)

I got an invitation to collaborate on the repository.
I never heard of this repo, and i don't know you

**Comment by Rubiidev-18** [comment]
I'm the main of rubiidev18alt. see https://github.com/Ajay-Pagar/youtube-clone-client/issues/1 for some context on what you should do.

**Comment by Bashamega** [comment]
Then why invite me. I don't know you and we never talked, so why invite me?

**Comment by Bashamega** [comment]
I only know you from bark
